[package]
name = "format-inplace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
get-selected-text = "0.1.6"
logos = "0.14.1"
petgraph = "0.6.5"
windows-hotkeys = "0.2.1"
